### PR TITLE
fix(volume): mute/unmute channels to support Safari for iPhone

### LINKED ISSUE #22: Volume slider not working on mobile devices V.1.1.0
Hi Marcos,
I’ve tested the latest release (1.1.0), but the issue still persists. The volume balance slider between the main room and interpreter channel doesn’t appear to have any effect — even when the slider is set to 100% interpreter, I can still hear the main room audio. The overall audio level remains unchanged regardless of the slider position.

Could you please confirm which Pexip version you tested where this was working as expected, and which mobile browsers and devices were used during your verification?
I’ve tried on multiple phones and browsers, but the behavior is consistently unchanged across all of them.

Interestingly, this feature works perfectly on PC, but not on mobile for some reason.
Do you know if the browser handles this functionality differently on mobile devices?

Thanks for looking into this!

Image

### PR DESCRIPTION
**Pull request by marcos-cereijo-pexip**
Closes https://github.com/pexip/plugin-interpretation/issues/22

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -15,3 +15,8 @@ export const capitalizeFirstLetter = (value: string): string => {
   const secondIndex = 1
   return value.charAt(firstIndex).toUpperCase() + value.slice(secondIndex)
 }
+
+export const isIOS = (): boolean =>
+  /iPad|iPhone|iPod/.test(navigator.userAgent) ||
+  // iPad on iOS 13 detection
+  (navigator.userAgent.includes('Mac') && 'ontouchend' in document)
```
Comment (timwilking) [inline src/utils.ts]: Could this be true on Touch-enabled Macs (if that exists) ? Could this be an issue ?

See: https://github.com/faisalman/ua-parser-js/blob/699f9c658ca61350d6e00387e2d59ba4e32fc10a/src/main/ua-parser.js#L1240

File: src/Widget/Volume/Volume.tsx [hunk 2]
```diff
@@ -12,13 +12,31 @@ export const Volume = (): React.JSX.Element => {
...
+  useEffect(() => {
+    // Set initial volume on mount for iOS devices
+    const minVolumeIOS = 0
+    const maxVolume = 100
+    if (isIOS() && hasMainFloorPriority) {
+      changeVolume(minVolumeIOS)
+    } else {
+      changeVolume(maxVolume)
+    }
+  }, [])
```
[the remark this answers is not in the document]
Comment (marcos-cereijo-pexip) [reply src/Widget/Volume/Volume.tsx:42]: It's intentionally. We only want to trigger this on mount.

File: src/utils.ts (hunk 1 above)
Comment (marcos-cereijo-pexip) [reply src/utils.ts]: I changed it only to:

```
export const isIOS = (): boolean =>
  /iPad|iPhone|iPod/.test(navigator.userAgent) 
  ```

**Review by timwilking — APPROVED** [review]
